services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: python3 -m flask run --host 0.0.0.0 --port 5000 --reload
